### PR TITLE
Upgrade to angular 5, including material.

### PR DESCRIPTION
**Pull request by fulv**

### CODE REVIEW

**Comment by ebrehault** [comment]
@fulv it looks like the tests are broken.

**Comment by fulv** [comment]
I'll look at them later.

Le jeu. 9 nov. 2017 à 09:25, Eric BREHAULT <notifications@github.com> a
écrit :

**Comment by ebrehault** [comment]
@fulv that was a very small detail, I had to compare with a brand new CLI 1.5 project to find it :)

**Comment by fulv** [comment]
@ebrehault thanks!

**Pull request merged**
