### PR TITLE
Added Icon type to control model

### PR DESCRIPTION
**Pull request by LuisPalomo**

### CODE REVIEW

**Review by mpellerin42 — COMMENTED** [review]
you need to:
- update the changelog
- update the version in package.json of the lib if you want to have this change tagged

**Comment by LuisPalomo** [comment]
@mpellerin42 ups! Sorry I completely forgot about that!

**Review by mpellerin42 — COMMENTED** [review]
I guess you want the icon model to use it in front-ui, and that's ok. But I feel like adding it without supporting it correctly wherever ControlModel is used in pastanaga can lead to bugs.
Do you need this change to be merged quickly? If not I would prefer you to check wherever ControlModel is used in Pastanaga and to manage the case where an IconModel is provided instead of a string.

**Comment by LuisPalomo** [comment]
@mpellerin42 I've already checked it and we currently support it, as you can see here:
https://github.com/plone/pastanaga-angular/blob/d30b12f954f67cec27a227e469ba1d41f7d4ac6e/projects/pastanaga/src/lib/controls/checkbox/checkbox.component.ts#L29
Seems like the person who introduced that change forgot about adding it to the model

**Review by mpellerin42 — APPROVED** [review]
Perfect then

**Pull request merged**
