### PR TITLE
ToastService: mark some properties as protected instead of private

### PR DESCRIPTION
**Pull request by mpellerin42**

### CODE REVIEW

**Review by dgsmith2 — CHANGES_REQUESTED** [review]
Why?

**Comment by mpellerin42** [comment]
> Why?

To implement a celebration toast in Atlas (same confetti animation as when tutorial last step is closed)

**Comment by dgsmith2** [comment]
Should we favor composition over inheritance?  If you are going to be creating a new feature should we instead do something like
```ts
public class CelebrationToastService {
constructor(
        private resolver: ComponentFactoryResolver,
        private rendererFactory: RendererFactory2,
        private appRef: ApplicationRef,
        private injector: Injector,
        private toastService: ToastService
    ) {}
    ...
}
```

I feel we should shy away updating the API of a standalone library to accommodate a specific use case in a dependency.

**Comment by dgsmith2** [comment]
Also, even in using `CelebrationToastService extends ToastService` you can still leave all injections `private` in both.

**Review by dgsmith2 — APPROVED** [review]

**Pull request merged**
